drop table if exists `user` CASCADE;
drop table if exists `genre` CASCADE;
drop table if exists `artist` CASCADE;
drop table if exists `playlist` CASCADE;
drop table if exists `album` CASCADE;
drop table if exists `track` CASCADE;
create table `user`
(
   id integer generated by default as identity,
   password VARCHAR (100) NOT NULL,
   username VARCHAR (100) NOT NULL,
   salt BINARY (255) NOT NULL,
   primary key (id)
);
create table `genre`
(
   id integer generated by default as identity,
   name VARCHAR (100) NOT NULL,
   description VARCHAR (100) NOT NULL,
   primary key (id)
);
create table `artist`
(
   id integer generated by default as identity,
   name VARCHAR (100) NOT NULL,
   primary key (id)
);
create table `playlist`
(
   id integer generated by default as identity,
   name VARCHAR (100) NOT NULL,
   description VARCHAR (100) NOT NULL,
   artwork VARCHAR (100) NOT NULL,
   primary key (id)
);
create table `album`
(
   id integer generated by default as identity,
   name VARCHAR (100) NOT NULL,
   cover VARCHAR (100),
   artist_id integer,
   genre_id integer,
   primary key (id)
);
create table `track`
(
   id integer generated by default as identity,
   name VARCHAR (100) NOT NULL,
   duration integer,
   lyrics VARCHAR (250),
   album_id integer,
   playlist_id integer,
   primary key (id)
);