drop table if exists `user` CASCADE;
drop table if exists `track` CASCADE;
drop table if exists `genre` CASCADE;
drop table if exists `artist` CASCADE;
create table `user` (
 id integer generated by default as identity,
 password VARCHAR(100) NOT NULL, 
 username VARCHAR(100) NOT NULL, 
 salt BINARY(255) NOT NULL,
 primary key (id)
);
create table `track` (
 id integer generated by default as identity,
 name VARCHAR(100) NOT NULL,
 duration integer(15) NOT NULL,
 lyrics VARCHAR(250) NOT NULL,
 primary key (id)
);