drop table if exists `user` CASCADE;
create table `user` (
 id integer generated by default as identity,
 password VARCHAR(100) NOT NULL, 
 username VARCHAR(100) NOT NULL, 
 salt BINARY(255) NOT NULL,
 primary key (id)
);
